// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.5
// source: federated.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelUpdateRequest_TrainingStatus int32

const (
	ModelUpdateRequest_SUCCEEDED ModelUpdateRequest_TrainingStatus = 0
	ModelUpdateRequest_FAILED    ModelUpdateRequest_TrainingStatus = 1
)

// Enum value maps for ModelUpdateRequest_TrainingStatus.
var (
	ModelUpdateRequest_TrainingStatus_name = map[int32]string{
		0: "SUCCEEDED",
		1: "FAILED",
	}
	ModelUpdateRequest_TrainingStatus_value = map[string]int32{
		"SUCCEEDED": 0,
		"FAILED":    1,
	}
)

func (x ModelUpdateRequest_TrainingStatus) Enum() *ModelUpdateRequest_TrainingStatus {
	p := new(ModelUpdateRequest_TrainingStatus)
	*p = x
	return p
}

func (x ModelUpdateRequest_TrainingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelUpdateRequest_TrainingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_federated_proto_enumTypes[0].Descriptor()
}

func (ModelUpdateRequest_TrainingStatus) Type() protoreflect.EnumType {
	return &file_federated_proto_enumTypes[0]
}

func (x ModelUpdateRequest_TrainingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelUpdateRequest_TrainingStatus.Descriptor instead.
func (ModelUpdateRequest_TrainingStatus) EnumDescriptor() ([]byte, []int) {
	return file_federated_proto_rawDescGZIP(), []int{0, 0}
}

type LayerWeights_LayerWeightsType int32

const (
	LayerWeights_UNKNOWN LayerWeights_LayerWeightsType = 0
	LayerWeights_ONE_D   LayerWeights_LayerWeightsType = 1
	LayerWeights_TWO_D   LayerWeights_LayerWeightsType = 2
)

// Enum value maps for LayerWeights_LayerWeightsType.
var (
	LayerWeights_LayerWeightsType_name = map[int32]string{
		0: "UNKNOWN",
		1: "ONE_D",
		2: "TWO_D",
	}
	LayerWeights_LayerWeightsType_value = map[string]int32{
		"UNKNOWN": 0,
		"ONE_D":   1,
		"TWO_D":   2,
	}
)

func (x LayerWeights_LayerWeightsType) Enum() *LayerWeights_LayerWeightsType {
	p := new(LayerWeights_LayerWeightsType)
	*p = x
	return p
}

func (x LayerWeights_LayerWeightsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LayerWeights_LayerWeightsType) Descriptor() protoreflect.EnumDescriptor {
	return file_federated_proto_enumTypes[1].Descriptor()
}

func (LayerWeights_LayerWeightsType) Type() protoreflect.EnumType {
	return &file_federated_proto_enumTypes[1]
}

func (x LayerWeights_LayerWeightsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LayerWeights_LayerWeightsType.Descriptor instead.
func (LayerWeights_LayerWeightsType) EnumDescriptor() ([]byte, []int) {
	return file_federated_proto_rawDescGZIP(), []int{2, 0}
}

type ModelUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModelId           string                            `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ModelType         int32                             `protobuf:"varint,10,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	LayersWeight      []byte                            `protobuf:"bytes,2,opt,name=layers_weight,json=layersWeight,proto3" json:"layers_weight,omitempty"`
	Status            ModelUpdateRequest_TrainingStatus `protobuf:"varint,3,opt,name=status,proto3,enum=protos.ModelUpdateRequest_TrainingStatus" json:"status,omitempty"`
	ClientId          int32                             `protobuf:"varint,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	BatchSize         int32                             `protobuf:"varint,6,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	RequestCounter    int32                             `protobuf:"varint,7,opt,name=request_counter,json=requestCounter,proto3" json:"request_counter,omitempty"`
	TotalClientsCount int32                             `protobuf:"varint,8,opt,name=total_clients_count,json=totalClientsCount,proto3" json:"total_clients_count,omitempty"`
	ClientLatestClock int32                             `protobuf:"varint,9,opt,name=client_latest_clock,json=clientLatestClock,proto3" json:"client_latest_clock,omitempty"`
}

func (x *ModelUpdateRequest) Reset() {
	*x = ModelUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_federated_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelUpdateRequest) ProtoMessage() {}

func (x *ModelUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federated_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelUpdateRequest.ProtoReflect.Descriptor instead.
func (*ModelUpdateRequest) Descriptor() ([]byte, []int) {
	return file_federated_proto_rawDescGZIP(), []int{0}
}

func (x *ModelUpdateRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ModelUpdateRequest) GetModelType() int32 {
	if x != nil {
		return x.ModelType
	}
	return 0
}

func (x *ModelUpdateRequest) GetLayersWeight() []byte {
	if x != nil {
		return x.LayersWeight
	}
	return nil
}

func (x *ModelUpdateRequest) GetStatus() ModelUpdateRequest_TrainingStatus {
	if x != nil {
		return x.Status
	}
	return ModelUpdateRequest_SUCCEEDED
}

func (x *ModelUpdateRequest) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *ModelUpdateRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *ModelUpdateRequest) GetRequestCounter() int32 {
	if x != nil {
		return x.RequestCounter
	}
	return 0
}

func (x *ModelUpdateRequest) GetTotalClientsCount() int32 {
	if x != nil {
		return x.TotalClientsCount
	}
	return 0
}

func (x *ModelUpdateRequest) GetClientLatestClock() int32 {
	if x != nil {
		return x.ClientLatestClock
	}
	return 0
}

type ModelWeights struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Layers            [][]byte `protobuf:"bytes,1,rep,name=layers,proto3" json:"layers,omitempty"`
	ModelClock        int32    `protobuf:"varint,2,opt,name=model_clock,json=modelClock,proto3" json:"model_clock,omitempty"`
	ClientId          int32    `protobuf:"varint,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientLatestClock int32    `protobuf:"varint,9,opt,name=client_latest_clock,json=clientLatestClock,proto3" json:"client_latest_clock,omitempty"`
}

func (x *ModelWeights) Reset() {
	*x = ModelWeights{}
	if protoimpl.UnsafeEnabled {
		mi := &file_federated_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelWeights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelWeights) ProtoMessage() {}

func (x *ModelWeights) ProtoReflect() protoreflect.Message {
	mi := &file_federated_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelWeights.ProtoReflect.Descriptor instead.
func (*ModelWeights) Descriptor() ([]byte, []int) {
	return file_federated_proto_rawDescGZIP(), []int{1}
}

func (x *ModelWeights) GetLayers() [][]byte {
	if x != nil {
		return x.Layers
	}
	return nil
}

func (x *ModelWeights) GetModelClock() int32 {
	if x != nil {
		return x.ModelClock
	}
	return 0
}

func (x *ModelWeights) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *ModelWeights) GetClientLatestClock() int32 {
	if x != nil {
		return x.ClientLatestClock
	}
	return 0
}

type LayerWeights struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WeightType  LayerWeights_LayerWeightsType `protobuf:"varint,1,opt,name=weight_type,json=weightType,proto3,enum=protos.LayerWeights_LayerWeightsType" json:"weight_type,omitempty"`
	OneDWeights []float64                     `protobuf:"fixed64,2,rep,packed,name=one_d_weights,json=oneDWeights,proto3" json:"one_d_weights,omitempty"`
	TwoDWeights [][]byte                      `protobuf:"bytes,3,rep,name=two_d_weights,json=twoDWeights,proto3" json:"two_d_weights,omitempty"`
	LayerRank   int32                         `protobuf:"varint,4,opt,name=layer_rank,json=layerRank,proto3" json:"layer_rank,omitempty"`
}

func (x *LayerWeights) Reset() {
	*x = LayerWeights{}
	if protoimpl.UnsafeEnabled {
		mi := &file_federated_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LayerWeights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerWeights) ProtoMessage() {}

func (x *LayerWeights) ProtoReflect() protoreflect.Message {
	mi := &file_federated_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerWeights.ProtoReflect.Descriptor instead.
func (*LayerWeights) Descriptor() ([]byte, []int) {
	return file_federated_proto_rawDescGZIP(), []int{2}
}

func (x *LayerWeights) GetWeightType() LayerWeights_LayerWeightsType {
	if x != nil {
		return x.WeightType
	}
	return LayerWeights_UNKNOWN
}

func (x *LayerWeights) GetOneDWeights() []float64 {
	if x != nil {
		return x.OneDWeights
	}
	return nil
}

func (x *LayerWeights) GetTwoDWeights() [][]byte {
	if x != nil {
		return x.TwoDWeights
	}
	return nil
}

func (x *LayerWeights) GetLayerRank() int32 {
	if x != nil {
		return x.LayerRank
	}
	return 0
}

type LayerTwoDWeights struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Weights []float64 `protobuf:"fixed64,1,rep,packed,name=weights,proto3" json:"weights,omitempty"`
}

func (x *LayerTwoDWeights) Reset() {
	*x = LayerTwoDWeights{}
	if protoimpl.UnsafeEnabled {
		mi := &file_federated_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LayerTwoDWeights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerTwoDWeights) ProtoMessage() {}

func (x *LayerTwoDWeights) ProtoReflect() protoreflect.Message {
	mi := &file_federated_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerTwoDWeights.ProtoReflect.Descriptor instead.
func (*LayerTwoDWeights) Descriptor() ([]byte, []int) {
	return file_federated_proto_rawDescGZIP(), []int{3}
}

func (x *LayerTwoDWeights) GetWeights() []float64 {
	if x != nil {
		return x.Weights
	}
	return nil
}

var File_federated_proto protoreflect.FileDescriptor

var file_federated_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x1a, 0x0c, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa8, 0x03, 0x0a, 0x12, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x73, 0x5f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0c, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x41, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69,
	0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x62, 0x61, 0x74, 0x63, 0x68, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x27, 0x0a, 0x0f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x13, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x11, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f,
	0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x11, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74,
	0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x2b, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e,
	0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x55, 0x43, 0x43, 0x45,
	0x45, 0x44, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44,
	0x10, 0x01, 0x22, 0x94, 0x01, 0x0a, 0x0c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x57, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0c, 0x52, 0x06, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1b, 0x0a, 0x09,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x13, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x63, 0x6c, 0x6f, 0x63, 0x6b,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4c, 0x61,
	0x74, 0x65, 0x73, 0x74, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0xf4, 0x01, 0x0a, 0x0c, 0x4c, 0x61,
	0x79, 0x65, 0x72, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x12, 0x46, 0x0a, 0x0b, 0x77, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x57, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x57, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x6f, 0x6e, 0x65, 0x5f, 0x64, 0x5f, 0x77, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x01, 0x52, 0x0b, 0x6f, 0x6e, 0x65, 0x44, 0x57,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x12, 0x22, 0x0a, 0x0d, 0x74, 0x77, 0x6f, 0x5f, 0x64, 0x5f,
	0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0b, 0x74,
	0x77, 0x6f, 0x44, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x5f, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x6b, 0x22, 0x35, 0x0a, 0x10, 0x4c, 0x61, 0x79,
	0x65, 0x72, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a,
	0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4f, 0x4e,
	0x45, 0x5f, 0x44, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x57, 0x4f, 0x5f, 0x44, 0x10, 0x02,
	0x22, 0x2c, 0x0a, 0x10, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x77, 0x6f, 0x44, 0x57, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x07, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73, 0x32, 0x91,
	0x01, 0x0a, 0x10, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x10, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x31, 0x0a, 0x11, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_federated_proto_rawDescOnce sync.Once
	file_federated_proto_rawDescData = file_federated_proto_rawDesc
)

func file_federated_proto_rawDescGZIP() []byte {
	file_federated_proto_rawDescOnce.Do(func() {
		file_federated_proto_rawDescData = protoimpl.X.CompressGZIP(file_federated_proto_rawDescData)
	})
	return file_federated_proto_rawDescData
}

var file_federated_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_federated_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_federated_proto_goTypes = []interface{}{
	(ModelUpdateRequest_TrainingStatus)(0), // 0: protos.ModelUpdateRequest.TrainingStatus
	(LayerWeights_LayerWeightsType)(0),     // 1: protos.LayerWeights.LayerWeightsType
	(*ModelUpdateRequest)(nil),             // 2: protos.ModelUpdateRequest
	(*ModelWeights)(nil),                   // 3: protos.ModelWeights
	(*LayerWeights)(nil),                   // 4: protos.LayerWeights
	(*LayerTwoDWeights)(nil),               // 5: protos.LayerTwoDWeights
	(*Empty)(nil),                          // 6: protos.Empty
}
var file_federated_proto_depIdxs = []int32{
	0, // 0: protos.ModelUpdateRequest.status:type_name -> protos.ModelUpdateRequest.TrainingStatus
	1, // 1: protos.LayerWeights.weight_type:type_name -> protos.LayerWeights.LayerWeightsType
	2, // 2: protos.FederatedService.TrainUpdateModel:input_type -> protos.ModelUpdateRequest
	6, // 3: protos.FederatedService.ChangeModeRestart:input_type -> protos.Empty
	2, // 4: protos.FederatedService.TrainUpdateModel:output_type -> protos.ModelUpdateRequest
	6, // 5: protos.FederatedService.ChangeModeRestart:output_type -> protos.Empty
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_federated_proto_init() }
func file_federated_proto_init() {
	if File_federated_proto != nil {
		return
	}
	file_shared_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_federated_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_federated_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelWeights); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_federated_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LayerWeights); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_federated_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LayerTwoDWeights); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_federated_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_federated_proto_goTypes,
		DependencyIndexes: file_federated_proto_depIdxs,
		EnumInfos:         file_federated_proto_enumTypes,
		MessageInfos:      file_federated_proto_msgTypes,
	}.Build()
	File_federated_proto = out.File
	file_federated_proto_rawDesc = nil
	file_federated_proto_goTypes = nil
	file_federated_proto_depIdxs = nil
}
