# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crdtv2.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='crdtv2.proto',
  package='protos',
  syntax='proto3',
  serialized_options=b'Z\t./;protos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x63rdtv2.proto\x12\x06protos\"J\n\nCRDTObject\x12\x16\n\x0e\x63rdt_object_id\x18\x01 \x01(\t\x12$\n\x04head\x18\x04 \x01(\x0b\x32\x16.protos.CRDTObjectNode\"(\n\tCRDTClock\x12\x0c\n\x04seed\x18\x01 \x01(\x03\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\"\xc7\x02\n\x0e\x43RDTObjectNode\x12,\n\x03map\x18\x01 \x03(\x0b\x32\x1f.protos.CRDTObjectNode.MapEntry\x12#\n\tg_counter\x18\x04 \x01(\x0b\x32\x10.protos.GCounter\x12\'\n\x0bmv_register\x18\x05 \x01(\x0b\x32\x12.protos.MVRegister\x12*\n\x0flast_operations\x18\x07 \x03(\x0b\x32\x11.protos.CRDTClock\x12\x11\n\tmap_value\x18\x08 \x01(\t\x12\x36\n\x13g_counter_federated\x18\t \x01(\x0b\x32\x19.protos.GCounterFederated\x1a\x42\n\x08MapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.protos.CRDTObjectNode:\x02\x38\x01\"W\n\x12\x43RDTOperationsList\x12\x16\n\x0e\x63rdt_object_id\x18\x01 \x01(\t\x12)\n\noperations\x18\x02 \x03(\x0b\x32\x15.protos.CRDTOperation\"\x8a\x02\n\rCRDTOperation\x12\x14\n\x0coperation_id\x18\x01 \x01(\t\x12\x16\n\x0eoperation_path\x18\x02 \x03(\t\x12\x0b\n\x03key\x18\x05 \x01(\t\x12\x33\n\nvalue_type\x18\x06 \x01(\x0e\x32\x1f.protos.CRDTOperation.ValueType\x12\r\n\x05value\x18\x07 \x01(\t\x12\r\n\x05\x63lock\x18\t \x01(\t\"k\n\tValueType\x12\x0e\n\nNOTYPECRDT\x10\x00\x12\x07\n\x03MAP\x10\x01\x12\r\n\tG_COUNTER\x10\x02\x12\x0f\n\x0bMV_REGISTER\x10\x03\x12\r\n\tFEDERATED\x10\x04\x12\x16\n\x12MV_REGISTER_STRING\x10\x05\" \n\x08GCounter\x12\x14\n\x0c\x63ounterValue\x18\x01 \x01(\x05\"C\n\nMVRegister\x12\x16\n\x0eregister_value\x18\x01 \x03(\x08\x12\x1d\n\x15register_value_string\x18\x02 \x03(\t\"8\n\x11GCounterFederated\x12\x14\n\x0c\x63ounterValue\x18\x01 \x01(\x01\x12\r\n\x05\x63lock\x18\x02 \x01(\x03*\x1e\n\x08TimeBase\x12\x08\n\x04ZERO\x10\x00\x12\x08\n\x04\x42\x41SE\x10\nB\x0bZ\t./;protosb\x06proto3'
)

_TIMEBASE = _descriptor.EnumDescriptor(
  name='TimeBase',
  full_name='protos.TimeBase',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ZERO', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BASE', index=1, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=991,
  serialized_end=1021,
)
_sym_db.RegisterEnumDescriptor(_TIMEBASE)

TimeBase = enum_type_wrapper.EnumTypeWrapper(_TIMEBASE)
ZERO = 0
BASE = 10


_CRDTOPERATION_VALUETYPE = _descriptor.EnumDescriptor(
  name='ValueType',
  full_name='protos.CRDTOperation.ValueType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOTYPECRDT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MAP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='G_COUNTER', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MV_REGISTER', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FEDERATED', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MV_REGISTER_STRING', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=721,
  serialized_end=828,
)
_sym_db.RegisterEnumDescriptor(_CRDTOPERATION_VALUETYPE)


_CRDTOBJECT = _descriptor.Descriptor(
  name='CRDTObject',
  full_name='protos.CRDTObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='crdt_object_id', full_name='protos.CRDTObject.crdt_object_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='head', full_name='protos.CRDTObject.head', index=1,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=98,
)


_CRDTCLOCK = _descriptor.Descriptor(
  name='CRDTClock',
  full_name='protos.CRDTClock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='seed', full_name='protos.CRDTClock.seed', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='protos.CRDTClock.count', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=140,
)


_CRDTOBJECTNODE_MAPENTRY = _descriptor.Descriptor(
  name='MapEntry',
  full_name='protos.CRDTObjectNode.MapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='protos.CRDTObjectNode.MapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='protos.CRDTObjectNode.MapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=404,
  serialized_end=470,
)

_CRDTOBJECTNODE = _descriptor.Descriptor(
  name='CRDTObjectNode',
  full_name='protos.CRDTObjectNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='map', full_name='protos.CRDTObjectNode.map', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='g_counter', full_name='protos.CRDTObjectNode.g_counter', index=1,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mv_register', full_name='protos.CRDTObjectNode.mv_register', index=2,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_operations', full_name='protos.CRDTObjectNode.last_operations', index=3,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='map_value', full_name='protos.CRDTObjectNode.map_value', index=4,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='g_counter_federated', full_name='protos.CRDTObjectNode.g_counter_federated', index=5,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CRDTOBJECTNODE_MAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=470,
)


_CRDTOPERATIONSLIST = _descriptor.Descriptor(
  name='CRDTOperationsList',
  full_name='protos.CRDTOperationsList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='crdt_object_id', full_name='protos.CRDTOperationsList.crdt_object_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operations', full_name='protos.CRDTOperationsList.operations', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=472,
  serialized_end=559,
)


_CRDTOPERATION = _descriptor.Descriptor(
  name='CRDTOperation',
  full_name='protos.CRDTOperation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation_id', full_name='protos.CRDTOperation.operation_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operation_path', full_name='protos.CRDTOperation.operation_path', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='protos.CRDTOperation.key', index=2,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value_type', full_name='protos.CRDTOperation.value_type', index=3,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='protos.CRDTOperation.value', index=4,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clock', full_name='protos.CRDTOperation.clock', index=5,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CRDTOPERATION_VALUETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=562,
  serialized_end=828,
)


_GCOUNTER = _descriptor.Descriptor(
  name='GCounter',
  full_name='protos.GCounter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='counterValue', full_name='protos.GCounter.counterValue', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=830,
  serialized_end=862,
)


_MVREGISTER = _descriptor.Descriptor(
  name='MVRegister',
  full_name='protos.MVRegister',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='register_value', full_name='protos.MVRegister.register_value', index=0,
      number=1, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='register_value_string', full_name='protos.MVRegister.register_value_string', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=864,
  serialized_end=931,
)


_GCOUNTERFEDERATED = _descriptor.Descriptor(
  name='GCounterFederated',
  full_name='protos.GCounterFederated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='counterValue', full_name='protos.GCounterFederated.counterValue', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clock', full_name='protos.GCounterFederated.clock', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=933,
  serialized_end=989,
)

_CRDTOBJECT.fields_by_name['head'].message_type = _CRDTOBJECTNODE
_CRDTOBJECTNODE_MAPENTRY.fields_by_name['value'].message_type = _CRDTOBJECTNODE
_CRDTOBJECTNODE_MAPENTRY.containing_type = _CRDTOBJECTNODE
_CRDTOBJECTNODE.fields_by_name['map'].message_type = _CRDTOBJECTNODE_MAPENTRY
_CRDTOBJECTNODE.fields_by_name['g_counter'].message_type = _GCOUNTER
_CRDTOBJECTNODE.fields_by_name['mv_register'].message_type = _MVREGISTER
_CRDTOBJECTNODE.fields_by_name['last_operations'].message_type = _CRDTCLOCK
_CRDTOBJECTNODE.fields_by_name['g_counter_federated'].message_type = _GCOUNTERFEDERATED
_CRDTOPERATIONSLIST.fields_by_name['operations'].message_type = _CRDTOPERATION
_CRDTOPERATION.fields_by_name['value_type'].enum_type = _CRDTOPERATION_VALUETYPE
_CRDTOPERATION_VALUETYPE.containing_type = _CRDTOPERATION
DESCRIPTOR.message_types_by_name['CRDTObject'] = _CRDTOBJECT
DESCRIPTOR.message_types_by_name['CRDTClock'] = _CRDTCLOCK
DESCRIPTOR.message_types_by_name['CRDTObjectNode'] = _CRDTOBJECTNODE
DESCRIPTOR.message_types_by_name['CRDTOperationsList'] = _CRDTOPERATIONSLIST
DESCRIPTOR.message_types_by_name['CRDTOperation'] = _CRDTOPERATION
DESCRIPTOR.message_types_by_name['GCounter'] = _GCOUNTER
DESCRIPTOR.message_types_by_name['MVRegister'] = _MVREGISTER
DESCRIPTOR.message_types_by_name['GCounterFederated'] = _GCOUNTERFEDERATED
DESCRIPTOR.enum_types_by_name['TimeBase'] = _TIMEBASE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CRDTObject = _reflection.GeneratedProtocolMessageType('CRDTObject', (_message.Message,), {
  'DESCRIPTOR' : _CRDTOBJECT,
  '__module__' : 'crdtv2_pb2'
  # @@protoc_insertion_point(class_scope:protos.CRDTObject)
  })
_sym_db.RegisterMessage(CRDTObject)

CRDTClock = _reflection.GeneratedProtocolMessageType('CRDTClock', (_message.Message,), {
  'DESCRIPTOR' : _CRDTCLOCK,
  '__module__' : 'crdtv2_pb2'
  # @@protoc_insertion_point(class_scope:protos.CRDTClock)
  })
_sym_db.RegisterMessage(CRDTClock)

CRDTObjectNode = _reflection.GeneratedProtocolMessageType('CRDTObjectNode', (_message.Message,), {

  'MapEntry' : _reflection.GeneratedProtocolMessageType('MapEntry', (_message.Message,), {
    'DESCRIPTOR' : _CRDTOBJECTNODE_MAPENTRY,
    '__module__' : 'crdtv2_pb2'
    # @@protoc_insertion_point(class_scope:protos.CRDTObjectNode.MapEntry)
    })
  ,
  'DESCRIPTOR' : _CRDTOBJECTNODE,
  '__module__' : 'crdtv2_pb2'
  # @@protoc_insertion_point(class_scope:protos.CRDTObjectNode)
  })
_sym_db.RegisterMessage(CRDTObjectNode)
_sym_db.RegisterMessage(CRDTObjectNode.MapEntry)

CRDTOperationsList = _reflection.GeneratedProtocolMessageType('CRDTOperationsList', (_message.Message,), {
  'DESCRIPTOR' : _CRDTOPERATIONSLIST,
  '__module__' : 'crdtv2_pb2'
  # @@protoc_insertion_point(class_scope:protos.CRDTOperationsList)
  })
_sym_db.RegisterMessage(CRDTOperationsList)

CRDTOperation = _reflection.GeneratedProtocolMessageType('CRDTOperation', (_message.Message,), {
  'DESCRIPTOR' : _CRDTOPERATION,
  '__module__' : 'crdtv2_pb2'
  # @@protoc_insertion_point(class_scope:protos.CRDTOperation)
  })
_sym_db.RegisterMessage(CRDTOperation)

GCounter = _reflection.GeneratedProtocolMessageType('GCounter', (_message.Message,), {
  'DESCRIPTOR' : _GCOUNTER,
  '__module__' : 'crdtv2_pb2'
  # @@protoc_insertion_point(class_scope:protos.GCounter)
  })
_sym_db.RegisterMessage(GCounter)

MVRegister = _reflection.GeneratedProtocolMessageType('MVRegister', (_message.Message,), {
  'DESCRIPTOR' : _MVREGISTER,
  '__module__' : 'crdtv2_pb2'
  # @@protoc_insertion_point(class_scope:protos.MVRegister)
  })
_sym_db.RegisterMessage(MVRegister)

GCounterFederated = _reflection.GeneratedProtocolMessageType('GCounterFederated', (_message.Message,), {
  'DESCRIPTOR' : _GCOUNTERFEDERATED,
  '__module__' : 'crdtv2_pb2'
  # @@protoc_insertion_point(class_scope:protos.GCounterFederated)
  })
_sym_db.RegisterMessage(GCounterFederated)


DESCRIPTOR._options = None
_CRDTOBJECTNODE_MAPENTRY._options = None
# @@protoc_insertion_point(module_scope)
