# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import federated_pb2 as federated__pb2
import shared_pb2 as shared__pb2


class FederatedServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TrainUpdateModel = channel.unary_unary(
                '/protos.FederatedService/TrainUpdateModel',
                request_serializer=federated__pb2.ModelUpdateRequest.SerializeToString,
                response_deserializer=federated__pb2.ModelUpdateRequest.FromString,
                )
        self.ChangeModeRestart = channel.unary_unary(
                '/protos.FederatedService/ChangeModeRestart',
                request_serializer=shared__pb2.Empty.SerializeToString,
                response_deserializer=shared__pb2.Empty.FromString,
                )


class FederatedServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TrainUpdateModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeModeRestart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TrainUpdateModel': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainUpdateModel,
                    request_deserializer=federated__pb2.ModelUpdateRequest.FromString,
                    response_serializer=federated__pb2.ModelUpdateRequest.SerializeToString,
            ),
            'ChangeModeRestart': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeModeRestart,
                    request_deserializer=shared__pb2.Empty.FromString,
                    response_serializer=shared__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.FederatedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FederatedService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TrainUpdateModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.FederatedService/TrainUpdateModel',
            federated__pb2.ModelUpdateRequest.SerializeToString,
            federated__pb2.ModelUpdateRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChangeModeRestart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.FederatedService/ChangeModeRestart',
            shared__pb2.Empty.SerializeToString,
            shared__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
