# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shared.proto',
  package='protos',
  syntax='proto3',
  serialized_options=b'Z\t./;protos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cshared.proto\x12\x06protos\"\x07\n\x05\x45mpty\"\xbb\x04\n\rOperationMode\x12+\n\rtarget_system\x18\x01 \x01(\x0e\x32\x14.protos.TargetSystem\x12\x1a\n\x12\x65ndorsement_policy\x18\x0c \x01(\x05\x12\x19\n\x11gossip_node_count\x18\x03 \x01(\x05\x12\x18\n\x10total_node_count\x18\x04 \x01(\x05\x12\x1a\n\x12total_client_count\x18\x05 \x01(\x05\x12\x1a\n\x12gossip_interval_ms\x18\x07 \x01(\x05\x12\"\n\x1atransaction_timeout_second\x18\x08 \x01(\x05\x12\x19\n\x11\x62lock_time_out_ms\x18\n \x01(\x05\x12\x1e\n\x16\x62lock_transaction_size\x18\x0b \x01(\x05\x12+\n#proposal_queue_consumption_rate_tps\x18\x0e \x01(\x05\x12.\n&transaction_queue_consumption_rate_tps\x18\x0f \x01(\x05\x12\x11\n\tbenchmark\x18\x10 \x01(\t\x12 \n\x18queue_ticker_duration_ms\x18\x11 \x01(\x05\x12\x1e\n\x16\x65xtra_endorsement_orgs\x18\x12 \x01(\x05\x12\x19\n\x11profiling_enabled\x18\x13 \x01(\t\x12&\n\x1eorgs_percentage_increased_load\x18\x14 \x01(\x05\x12 \n\x18load_increase_percentage\x18\x15 \x01(\x05\"[\n\x12\x46\x61ilureCommandMode\x12\x1a\n\x12\x66\x61ilure_duration_s\x18\x01 \x01(\x05\x12)\n\x0c\x66\x61ilure_type\x18\x02 \x01(\x0e\x32\x13.protos.FailureType\"t\n\tProfiling\x12\x37\n\x0eprofiling_type\x18\x01 \x01(\x0e\x32\x1f.protos.Profiling.ProfilingType\".\n\rProfilingType\x12\x08\n\x04NONE\x10\x00\x12\x07\n\x03\x43PU\x10\x01\x12\n\n\x06MEMORY\x10\x02\"\"\n\x0fProfilingResult\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c*H\n\x0cTargetSystem\x12\x10\n\x0cNOTYPESYSTEM\x10\x00\x12\x0f\n\x0bORDERLESSFL\x10\x01\x12\x15\n\x11\x46\x45\x44\x45RATEDLEARNING\x10\x04*Z\n\x0b\x46\x61ilureType\x12\x11\n\rNOTYPEFAILURE\x10\x00\x12\x0b\n\x07\x43RASHED\x10\x01\x12\x0c\n\x08TAMPERED\x10\x02\x12\x11\n\rNOTRESPONDING\x10\x03\x12\n\n\x06RANODM\x10\x04\x42\x0bZ\t./;protosb\x06proto3'
)

_TARGETSYSTEM = _descriptor.EnumDescriptor(
  name='TargetSystem',
  full_name='protos.TargetSystem',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOTYPESYSTEM', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ORDERLESSFL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FEDERATEDLEARNING', index=2, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=854,
  serialized_end=926,
)
_sym_db.RegisterEnumDescriptor(_TARGETSYSTEM)

TargetSystem = enum_type_wrapper.EnumTypeWrapper(_TARGETSYSTEM)
_FAILURETYPE = _descriptor.EnumDescriptor(
  name='FailureType',
  full_name='protos.FailureType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOTYPEFAILURE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CRASHED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TAMPERED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NOTRESPONDING', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RANODM', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=928,
  serialized_end=1018,
)
_sym_db.RegisterEnumDescriptor(_FAILURETYPE)

FailureType = enum_type_wrapper.EnumTypeWrapper(_FAILURETYPE)
NOTYPESYSTEM = 0
ORDERLESSFL = 1
FEDERATEDLEARNING = 4
NOTYPEFAILURE = 0
CRASHED = 1
TAMPERED = 2
NOTRESPONDING = 3
RANODM = 4


_PROFILING_PROFILINGTYPE = _descriptor.EnumDescriptor(
  name='ProfilingType',
  full_name='protos.Profiling.ProfilingType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CPU', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MEMORY', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=770,
  serialized_end=816,
)
_sym_db.RegisterEnumDescriptor(_PROFILING_PROFILINGTYPE)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='protos.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=31,
)


_OPERATIONMODE = _descriptor.Descriptor(
  name='OperationMode',
  full_name='protos.OperationMode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='target_system', full_name='protos.OperationMode.target_system', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='endorsement_policy', full_name='protos.OperationMode.endorsement_policy', index=1,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gossip_node_count', full_name='protos.OperationMode.gossip_node_count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_node_count', full_name='protos.OperationMode.total_node_count', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_client_count', full_name='protos.OperationMode.total_client_count', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gossip_interval_ms', full_name='protos.OperationMode.gossip_interval_ms', index=5,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transaction_timeout_second', full_name='protos.OperationMode.transaction_timeout_second', index=6,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='block_time_out_ms', full_name='protos.OperationMode.block_time_out_ms', index=7,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='block_transaction_size', full_name='protos.OperationMode.block_transaction_size', index=8,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='proposal_queue_consumption_rate_tps', full_name='protos.OperationMode.proposal_queue_consumption_rate_tps', index=9,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transaction_queue_consumption_rate_tps', full_name='protos.OperationMode.transaction_queue_consumption_rate_tps', index=10,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='benchmark', full_name='protos.OperationMode.benchmark', index=11,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='queue_ticker_duration_ms', full_name='protos.OperationMode.queue_ticker_duration_ms', index=12,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extra_endorsement_orgs', full_name='protos.OperationMode.extra_endorsement_orgs', index=13,
      number=18, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='profiling_enabled', full_name='protos.OperationMode.profiling_enabled', index=14,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orgs_percentage_increased_load', full_name='protos.OperationMode.orgs_percentage_increased_load', index=15,
      number=20, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='load_increase_percentage', full_name='protos.OperationMode.load_increase_percentage', index=16,
      number=21, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=605,
)


_FAILURECOMMANDMODE = _descriptor.Descriptor(
  name='FailureCommandMode',
  full_name='protos.FailureCommandMode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='failure_duration_s', full_name='protos.FailureCommandMode.failure_duration_s', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='failure_type', full_name='protos.FailureCommandMode.failure_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=607,
  serialized_end=698,
)


_PROFILING = _descriptor.Descriptor(
  name='Profiling',
  full_name='protos.Profiling',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='profiling_type', full_name='protos.Profiling.profiling_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PROFILING_PROFILINGTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=700,
  serialized_end=816,
)


_PROFILINGRESULT = _descriptor.Descriptor(
  name='ProfilingResult',
  full_name='protos.ProfilingResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='protos.ProfilingResult.content', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=818,
  serialized_end=852,
)

_OPERATIONMODE.fields_by_name['target_system'].enum_type = _TARGETSYSTEM
_FAILURECOMMANDMODE.fields_by_name['failure_type'].enum_type = _FAILURETYPE
_PROFILING.fields_by_name['profiling_type'].enum_type = _PROFILING_PROFILINGTYPE
_PROFILING_PROFILINGTYPE.containing_type = _PROFILING
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['OperationMode'] = _OPERATIONMODE
DESCRIPTOR.message_types_by_name['FailureCommandMode'] = _FAILURECOMMANDMODE
DESCRIPTOR.message_types_by_name['Profiling'] = _PROFILING
DESCRIPTOR.message_types_by_name['ProfilingResult'] = _PROFILINGRESULT
DESCRIPTOR.enum_types_by_name['TargetSystem'] = _TARGETSYSTEM
DESCRIPTOR.enum_types_by_name['FailureType'] = _FAILURETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'shared_pb2'
  # @@protoc_insertion_point(class_scope:protos.Empty)
  })
_sym_db.RegisterMessage(Empty)

OperationMode = _reflection.GeneratedProtocolMessageType('OperationMode', (_message.Message,), {
  'DESCRIPTOR' : _OPERATIONMODE,
  '__module__' : 'shared_pb2'
  # @@protoc_insertion_point(class_scope:protos.OperationMode)
  })
_sym_db.RegisterMessage(OperationMode)

FailureCommandMode = _reflection.GeneratedProtocolMessageType('FailureCommandMode', (_message.Message,), {
  'DESCRIPTOR' : _FAILURECOMMANDMODE,
  '__module__' : 'shared_pb2'
  # @@protoc_insertion_point(class_scope:protos.FailureCommandMode)
  })
_sym_db.RegisterMessage(FailureCommandMode)

Profiling = _reflection.GeneratedProtocolMessageType('Profiling', (_message.Message,), {
  'DESCRIPTOR' : _PROFILING,
  '__module__' : 'shared_pb2'
  # @@protoc_insertion_point(class_scope:protos.Profiling)
  })
_sym_db.RegisterMessage(Profiling)

ProfilingResult = _reflection.GeneratedProtocolMessageType('ProfilingResult', (_message.Message,), {
  'DESCRIPTOR' : _PROFILINGRESULT,
  '__module__' : 'shared_pb2'
  # @@protoc_insertion_point(class_scope:protos.ProfilingResult)
  })
_sym_db.RegisterMessage(ProfilingResult)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
